name: Keep Supabase Project Awake

on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase endpoint
        run: |
          curl -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/ping?select=id" \
          -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}"
